name: Compile zsign

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache OpenSSL
      uses: actions/cache@v2
      with:
        path: |
          *.deb
        key: ${{ runner.os }}-openssl-${{ hashFiles('*.deb') }}
        restore-keys: |
          ${{ runner.os }}-openssl-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip build-essential checkinstall zlib1g-dev wget g++ cmake make checkinstall zlib1g-dev
        sudo apt-get install libssl-dev
        sudo apt-get install -y openssl=1.1.1-1ubuntu2.1~18.04.6 libssl-dev
        
    - name: Compile zsign
      run: |
        g++ *.cpp common/*.cpp -lcrypto -O3 -o zsign
